sudo: required

language: go

services:
  - docker

env:
  - COMMAND=checkContainer
  - COMMAND=checkImage
  - COMMAND=pull
  - COMMAND=rm
  - COMMAND=run
  - COMMAND=stop

go:
  - 1.9.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - go build

script:
  - go test ./... -v
  - .travis/tests-${COMMAND}.sh