sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

env:
  - LPN_COMMAND=checkContainer
  - LPN_COMMAND=checkImage
  - LPN_COMMAND=deploy
  - LPN_COMMAND=license
  - LPN_COMMAND=pull
  - LPN_COMMAND=rm
  - LPN_COMMAND=rmi
  - LPN_COMMAND=run
  - LPN_COMMAND=start
  - LPN_COMMAND=stop
  - LPN_COMMAND=tags
  - LPN_COMMAND=version

before_install:
  - sudo apt update -y
  - sudo apt install realpath -y
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - gem install aruba
  - curl https://cdn.wedeploy.com/cli/latest/wedeploy.sh -sL | bash

install:
  - |
    if [ "$LPN_COMMAND" != ""] && ["$LPN_COMMAND" != "license" ] && [ "$LPN_COMMAND" != "tags" ] && [ "$LPN_COMMAND" != "version" ]; then
      ./scripts/pull-images.sh
    fi
  - go build

script:
  - |
    if [ "$LPN_COMMAND" != "" ]; then
      mkdir bin && mv ./lpn bin/lpn && cucumber features/$LPN_COMMAND.feature
    fi