sudo: required

language: go

services:
  - docker

env:
  - COMMAND=checkContainer
  - COMMAND=checkImage
  - COMMAND=deploy
  - COMMAND=pull
  - COMMAND=rm
  - COMMAND=run
  - COMMAND=stop

go:
  - 1.9.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - go build

script:
  - ./scripts/coverage.sh
  - ./scripts/tests-${COMMAND}.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
 provider: script
 script: cd $TRAVIS_BUILD_DIR && .equinox/release.sh
 on:
   branch: master