language: go

env:
  global:
    - DEP_VERSION="0.4.1"
env:
  - COMMAND=checkContainer
  - COMMAND=checkImage
  - COMMAND=pull
  - COMMAND=rm
  - COMMAND=run
  - COMMAND=stop

go:
  - 1.9.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - go build

script:
  - go test ./...
  - .travis/tests-${COMMAND}.sh