sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

env:
  - COMMAND=checkContainer
  - COMMAND=checkImage
  - COMMAND=deploy
  - COMMAND=pull
  - COMMAND=rm
  - COMMAND=run
  - COMMAND=stop

stages:
  - build
  - unit tests
  - test
  - release

jobs:
  include:
    - stage: build
      script: go build
      env: STAGE=noTest
    - stage: unit tests
      script: ./scripts/coverage.sh
      env: STAGE=noTest
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      script: ./scripts/tests-${COMMAND}.sh
    - stage: release
      env: STAGE=noTest
      if: branch = master
      script: .equinox/release.sh