language: go

env:
  - DEP_VERSION="0.4.1"

go:
  - 1.8.x
  - 1.9.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script: go test ./...