sudo: required

language: go

services:
  - docker

go:
  - 1.12.x

env:
  global:
    - LPN_LOG_LEVEL=DEBUG
    - LPN_LOG_INCLUDE_TIMESTAMP=TRUE
  matrix:
    - LPN_COMMAND=checkc
    - LPN_COMMAND=checki
    - LPN_COMMAND=deploy
    - LPN_COMMAND=license
    - LPN_COMMAND=pull
    - LPN_COMMAND=rm
    - LPN_COMMAND=rmi
    - LPN_COMMAND=run
    - LPN_COMMAND=start
    - LPN_COMMAND=stop
    - LPN_COMMAND=tags
    - LPN_COMMAND=version

cache:
  directories:
    - ${HOME}/docker

before_cache:
  # Save tagged docker images
  - docker save -o ${HOME}/docker/images.tar $(docker images -a -q)

before_install:
  - ./.github/scripts/install-dependencies.sh
  # Load cached docker images
  - mkdir ${HOME}/docker && docker load -i ${HOME}/docker/images.tar || true

install:
  - |
    if [ "$LPN_COMMAND" != "license" ] && [ "$LPN_COMMAND" != "tags" ] && [ "$LPN_COMMAND" != "version" ]; then
      ./.github/scripts/pull-images.sh
    fi
  - GO111MODULE=on go build -o ./bin/lpn

script:
  - |
    gotestsum --format short-verbose ./...
    cucumber features/$LPN_COMMAND.feature